name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Ajuste para a branch principal do seu repositório

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ajuste conforme necessário

      - name: Instalar dependências
        working-directory: documentation
        run: npm install

      - name: Build do Docusaurus
        working-directory: documentation
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Fazer deploy para GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: documentation/build  # Diretório onde o Docusaurus gera o site

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v1
