name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Substitua pela branch principal do seu repositório, se necessário

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ajuste a versão do Node.js conforme necessário

      - name: Instalar dependências
        working-directory: documentation
        run: npm install

      - name: Build do Docusaurus
        working-directory: documentation
        run: npm run build

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: documentation/build  # O diretório correto onde Docusaurus gera os arquivos estáticos
          publish_branch: gh-pages  # Branch onde o site será publicado
          cname: ''  # Se for usar um domínio customizado, coloque o domínio aqui
